"""Regions for different S3-like storage"""

regions = {
    "S3": [
        "us-east-1",
        "us-east-2",
        "us-west-1",
        "us-west-2",
        "af-south-1",
        "ap-east-1",
        "ap-south-2",
        "ap-southeast-3",
        "ap-southeast-4",
        "ap-south-1",
        "ap-south-2",
        "ap-northeast-3",
        "ap-northeast-2",
        "ap-southeast-1",
        "ap-southeast-2",
        "ap-northeast-1",
        "ca-central-1",
        "cn-north-1",
        "cn-northwest-1",
        "eu-central-1",
        "eu-west-1",
        "eu-west-2",
        "eu-south-1",
        "eu-west-3",
        "eu-north-1",
        "eu-south-2",
        "eu-central-2",
        "sa-east-1",
        "me-south-1",
        "me-central-1",
        "us-gov-east-1",
        "us-gov-west-1",
    ],
    "R2": [
        "us-east-1",
    ],
    "COS(Tencent)": [
        "ap-beijing-1",
        "ap-beijing",
        "ap-nanjing",
        "ap-shanghai",
        "ap-guangzhou",
        "ap-chengdu",
        "ap-chongqing",
        "ap-shenzhen-fsi",
        "ap-shanghai-fsi",
        "ap-beijing-fsi",
        "ap-hongkong",
        "ap-singapore",
        "ap-mumbai",
        "ap-jakarta",
        "ap-seoul",
        "ap-bangkok",
        "ap-tokyo",
        "na-siliconvalley",
        "na-ashburn",
        "na-toronto",
        "sa-saopaulo",
        "eu-frankfurt",
    ],
}
